services:
  postgres:
    image: postgres:15.2
    container_name: scrapper_postgres
    restart: always
    environment:
      POSTGRES_DB: LinkTracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"

  liquibase-migrations:
    image: liquibase/liquibase:4.29
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - type: bind
        source: ./scrapper/src/main/resources/db/changelog
        target: /liquibase/changelog
      - type: bind
        source: ./lib/postgresql-42.7.3.jar
        target: /liquibase/lib/postgresql.jar
    command:
      - --searchPath=/liquibase/changelog
      - --changelog-file=db.changelog-master.xml
      - --url=jdbc:postgresql://postgres:5432/LinkTracker
      - --username=postgres
      - --password=1
      - --classpath=/liquibase/lib/postgresql.jar
      - update

