app:
  github-api-url: https://api.github.com
  stackoverflow-api-url: https://api.stackexchange.com/2.3
  github:
    token: ${GITHUB_TOKEN}
  stackOverflow:
    key: ${SO_KEY}
    accessToken: SO_ACCESS_TOKEN
  kafka:
    topic:
      notifications: link-updates-topic

bot:
  base-url: ${BOT_BASE_URL}

database:
  access-type: ORM

spring:
  application:
    name: Scrapper
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: public
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    user: postgres
    password: 1
    url: ${POSTGRES_URL}
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: validate
      default_schema: public
    open-in-view: false
  mvc:
    locale: ru_RU
    http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
