app:
  github-api-url: https://api.github.com
  stackoverflow-api-url: https://api.stackexchange.com/2.3
  github:
    token: YOUR_GITHUB_TOKEN
  stackOverflow:
    key: YOUR_STACKOVERFLOW_KEY
    accessToken: YOUR_STACKOVERFLOW_ACCESS_TOKEN

bot:
  base-url: http://localhost:8081

spring:
  application:
    name: Scrapper
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  mvc:
    locale: ru_RU
    http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
