app:
  telegram-token: ${TELEGRAM_TOKEN}

scrapper:
  base-url: ${SCRAPPER_BASE_URL}

bot:
  base-url: ${BOT_BASE_URL}

spring:
  application:
    name: DMLinkUpdateBot
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
